name: Unitests

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup VSTest.Console.exe
      uses: malcolmnixon/Setup-VSTest@master

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build Windows Project
      run: msbuild Emuander.sln /t:"UnitTest\Tests":Rebuild /p:Configuration="Release" /p:Platform="x64" /v:minimal

    - name: Run Unit Tests
      run: vstest.console .\Output\Tests\x64\Release\Tests.dll
